### ISSUE TITLE
More information needed on token format for ``/auth/jwt/verify`` - possible incorrect token

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#100]
For #48 (3.2), I tried sending the token received in the email URL in the following formats:  
- ``c7xdzq-f9473fbeced62e749422b6a98566bd8c``
- ``c7xdzq+f9473fbeced62e749422b6a98566bd8c``  
- ``c7xdzq.f9473fbeced62e749422b6a98566bd8c``
as strings, but I get a ``401 Unauthorized`` response ``Token invalid or expired``.  

[Djoser API documentation](https://djoser.readthedocs.io/en/latest/jwt_endpoints.html#jwt-verify) doesn't mention anything else than "token".  

Either the token being received in the email is incorrect, or there is a certain way it has to be formatted for the ``/auth/jwt/verify`` endpoint.

**Comment by seporterfield** [comment]
The following workflow works for me on feat/1_auth:

1. Hit the /auth/users/ endpoint to register
2. Receive activation email
3. Grab the uid and token from the activation email
4. Hit /auth/users/activation with the uid and token from email
5. User is activated
6. Hit /auth/jwt/create with the username and password
7. Get access and refresh tokens back

**Comment by Monstarrrr** [comment]
I see i've not been using the right endpoint (``/auth/jwt/verify`` instead of ``/auth/activation``)  

Thank you for the clarifications 🚀

**Comment by seporterfield** [comment]
/auth/users/activation 😉
