### ISSUE TITLE
Update decision automation flow

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#128]
### Currently 

We have to fill in the issue body with the ``_template.md`` manually to then send that body to the newly created decision file.

### Update  

Instead we could make the ``decision.yml`` auto-generate the decision file from the ``_template.md``

**Comment by seporterfield** [comment]
Go to the repo's [actions settings](https://github.com/Monstarrrr/rebutify/settings/actions) and turn on "Allow GitHub Actions to create and approve pull requests."

![image](https://github.com/Monstarrrr/rebutify/assets/107010978/de916aa0-ea98-410d-9be6-65f4ecebb6df)
@Monstarrrr

**Comment by Monstarrrr** [comment]
> Currently, the flow fails to create a pull request and prints instead `fatal: couldn't find remote ref create-pull-request/patch`.
> 
> This is most likely due to [this](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-inputs) step of the setup for the create-pull-request action not being completed.
> 
> To resolve this, go to the repo's [actions settings](https://github.com/Monstarrrr/rebutify/settings/actions) and turn on "Allow GitHub Actions to create and approve pull requests."
> 
> ![image](https://github.com/Monstarrrr/rebutify/assets/107010978/de916aa0-ea98-410d-9be6-65f4ecebb6df)
> @Monstarrrr

Done
