### ISSUE TITLE
Pre-commit fixes and updates

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#132]
- [x] Auto-update pre-commit libraries
- [x] Fix lack of linting, currently the "ruff" step only sorts imports!

**Comment by seporterfield** [comment]
@Monstarrrr fyi right place to assign reviewer is on PR,
Issue assignments are who works to solve the issue

**Comment by Monstarrrr** [comment]
> @Monstarrrr fyi right place to assign reviewer is on PR, Issue assignments are who works to solve the issue

Yes i'm aware, must have been a mistake
