### ISSUE TITLE
Modify API ViewSet: arguments with pagination

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#135]
~~Create~~/Modify an API ViewSet that gets arguments with pagination (get 10 arguments, get 25 arguments, get 50, get 100)

- [ ] Tests written
- [ ] Tests passing

EDIT:
The "create" part has been completed in https://github.com/Monstarrrr/rebutify/issues/216. 
The "modify" part is to be done here still

**Comment by Monstarrrr** [comment]
> Create/modify an API ViewSet that gets arguments with pagination (get 10 arguments, get 25 arguments, get 50, get 100)
> 
> - [ ] Tests written
> - [ ] Tests passing

Just to be clear, pagination would be a fixed number of arguments at different locations of the array of data, you don't increase the amount of data in the API answer. There is a parameter we could set to increase how much we want to be displayed per page, but that is something else.

**Comment by purple-void** [comment]
@seporterfield what do you mean tests written and tests passing?

**Comment by seporterfield** [comment]
The new features for this issue will have the corresponding tests
