### ISSUE TITLE
Mailgun Error: ``Domain is not allowed`` ; ``Please activate your mailgun account``

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#162]
## Full Error
> 421, b'Domain sandbox[XXXXX].mailgun.org is not allowed to send: Please activate your Mailgun account. Check your inbox or log in to your control panel to resend the activation email.  

## Consequence(s)
- Blocks registration
- Blocking #121

**Comment by Monstarrrr** [comment]
I thought about the 100 emails per day limit, but I did not reach it at all and it has been 2 days since I sent many (~50) emails in total within a day, we are past that date.
![image](https://github.com/Monstarrrr/rebutify/assets/31903668/10d2b649-e6b5-4f6c-9678-b796af3b5255)

**Comment by seporterfield** [comment]
Issue was Mailgun's new SMS-based email verification. Closing since this is vendor specific, see discord
