### ISSUE TITLE
Get confirmation emails to work again

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#173]
Blocking #121 

~~- [x] Register in new provider~~
~~- [x] Update DNS settings~~
~~- [ ] Update backend code~~
~~- [ ] ?~~
~~- [ ] Profit~~

- [x] Use local email

**Comment by seporterfield** [comment]
If you're relying on the account I set up with an SMTP provider, expect that to be blocked a little longer.
If you need one in the meantime, you can use your own email account to create an account with an SMTP provider to get email sending from localhost working.

No updates to backend code will be necessary. The only things that would change are the credentials for the SMTP provider (environment variables) or settings with the provider themselves (on their website).

In other news, we now have credentials for an SMTP service for production instances behind the domain rebutify.org that will work for an unlimited number of users.

**Comment by seporterfield** [comment]
Another way to unblock this would be to have a debug-mode-only backend view that can preview emails being sent so that we can work on tasks relying on email without the external dependency of an SMTP provider. Looking into this now.

**Comment by seporterfield** [comment]
#177 #179 would close this issue and unblock #121
