### ISSUE TITLE
Decide on Session Method (``JWT`` vs ``Session Storage``)

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#195]
- **Impact**: 🟢 Low

- **Status**: 🔓 Deciding...

- **Deciders & Confidence**:

  - @purple-void (? / 5️)
  - @seporterfield (5 / 5️)
  - @Monstarrrr (5 / 5️)

- **Last updated**: [17-06-2024]

## Decision Drivers

- Security
- Performance

## Considered Options 

| Feature                       | JWT                                      | Session Storage                          |
|----------------------------|------------------------------------|----------------------------------------|
| **Storage**                  | Client-side                            | Server-side                                 |
| **Statefulness**            | Stateless                               | Stateful                                       |
| **Scalability**               | High                                     | Moderate                                   |
| **Revocation**             | Difficult                                 | Easy                                            |
| **Security**                  | Risk of token compromise      | Server-side storage more secure  |
| **Ease of Use**            | Requires token handling         | Requires session management     |
| **Use Cases**              | APIs, SPAs, microservices        | Traditional web apps                   |

### JWT

1. Upon user authentication, the server generates a JWT.
2. This JWT is sent back to the client and stored, often in local storage or an HTTP-only cookie.
3. The client includes this token in the HTTP Authorization header for subsequent requests.
4. The server validates the token and grants access if valid.  

Advantages:

- Scalability: Due to their stateless nature, JWTs are ideal for distributed systems.
- Flexibility: They can be used across different domains and applications.
- Security: When properly implemented, they provide a secure way to handle user authentication.

Security Concerns:

- Transmission Security: It's vital to transmit JWTs over HTTPS.
- Storage: Store JWTs securely to prevent XSS attacks and other vulnerabilities.

### Session Storage

1. **User Authentication**: The user provides credentials, which the server verifies.
2. **Session Creation**: Upon successful authentication, the server creates a session record with a unique identifier, user identifier, session start time, expiry, and possibly additional context like IP address and User Agent. Stores that in Database.
3. **Cookie Storage**: This session identifier is sent back and stored as a cookie in the user’s browser.
4. **Session Validation**: Each request from the user’s browser includes this cookie, then server validates the session by querying to Database. If valid, the request is processed.

Advantages:

- Simplicity and Reliability: The server’s session record acts as a centralized truth source, making it straightforward to manage user sessions.
- Revocation Efficiency: Access can be quickly revoked by deleting or invalidating the session record, ensuring up-to-date session validity.

Disadvantages:

- Performance Issues at Scale: The dependency on database interactions for every session validation can introduce latency, particularly for high-traffic applications.
- Latency in Dynamic Environments: In applications with dynamic clients, this latency can impact user experience, making session-based authentication less ideal in such scenarios.

## Decision Outcome

**Chosen option**: 

**Reason**:

**Comment by seporterfield** [comment]
I'm not too concerned about performance since it's important to [build things that don't scale](https://paulgraham.com/ds.html).

That being said I'm at a solid 4 for chugging forward with JWTs in the spirit of trying things!

**Comment by Monstarrrr** [comment]
I vote for ``Session storage`` because ``JWT`` see no benefits in our case, only inconvenients (https://developer.okta.com/blog/2017/08/17/why-jwts-suck-as-session-tokens)

**Comment by seporterfield** [comment]
Then change my vote to a 5 for session storage

**Comment by Monstarrrr** [comment]
Implementing Session Storage in django might be tricky https://dev.to/rhymes/why-is-django-rest-framework-lying-to-me-3nan

**Comment by Monstarrrr** [comment]
I'll make an Issue for researching implementing Session Storage
