### ISSUE TITLE
Create ViewSet for Arguments

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#216]
PR #217 

Create an API ViewSet that gets/creates/etc. arguments.

- [ ] Tests written
- [ ] Tests passing

**Comment by Monstarrrr** [comment]
Blocking #4

**Comment by Monstarrrr** [comment]
Can you set these as not required ? 
![image](https://github.com/Monstarrrr/rebutify/assets/31903668/fdef4824-8502-41cd-88a4-15347102816a)

**Comment by seporterfield** [comment]
Everything sounds splendid 👍

**Comment by seporterfield** [comment]
hmm we shouldn't need to update the models at all for this. Is something missing?
Arguments fit cozily inside the posts table.

What needs changing is how the backend presents posts with id 1 (arguments). That means a new ViewSet.
