### ISSUE TITLE
``delete.auth/users/me`` returns Internal server error

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#218]
- Blocking #8 

![image](https://github.com/Monstarrrr/rebutify/assets/31903668/7a9fb470-8a5d-40f6-ab5d-fb04b420d871)

![image](https://github.com/Monstarrrr/rebutify/assets/31903668/28a67bf8-6d1c-47fb-9fbb-dc2f945634bc)

The endpoint is also not documented as there is no mention of ``current_password`` being required which I only found out (within the ``401`` response) after trying to call the endpoint without it at first :  
![image](https://github.com/Monstarrrr/rebutify/assets/31903668/807b5990-13bf-4259-acfd-7ca942124c0d)

**Comment by seporterfield** [comment]
Can you post the logs of the error you get when you provide the correct request body as in screenshot 1?

**Comment by Monstarrrr** [comment]
> Can you post the logs of the error you get when you provide the correct request body as in screenshot 1?

```cmd
Internal Server Error: /auth/users/me/
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)        
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\djoser\views.py", line 177, in me
    return self.destroy(request, *args, **kwargs)
  File "C:\Python310\lib\site-packages\djoser\views.py", line 163, in destroy
    utils.logout_user(self.request)
  File "C:\Python310\lib\site-packages\djoser\utils.py", line 26, in logout_user
cts'
[25/Jun/2024 17:01:41] "DELETE /auth/users/me/ HTTP/1.1" 500 112250
```

**Comment by seporterfield** [comment]
Call the endpoint with query params and it works
example: 
`curl -X 'DELETE' \
  'http://localhost:8000/auth/users/me?current_password=password123!/'`

**Comment by Monstarrrr** [comment]
> Call the endpoint with query params and it works example: `curl -X 'DELETE' \ 'http://localhost:8000/auth/users/me?current_password=password123!/'`

http://localhost:8000/auth/users/me?current_password=Password123  
returns ``404``  

http://localhost:8000/auth/users/me?current_password=Password123  
(with a ``/`` after ``/me``)
returns the expected route page but with the ``400`` error 

![Image](https://github.com/Monstarrrr/rebutify/assets/31903668/ac6b1c91-8da5-48a8-9f34-c9c1b213671d)

**Comment by seporterfield** [comment]
Screenshot has `me?/...`
Try `me?current_password.../`

**Comment by seporterfield** [comment]
Want to go with this unsafe practice for the MVP? The accounts get deleted anyway- still not great to have links with passwords in them clientside though

Alternative is a custom View/APIView for account deletion

**Comment by Monstarrrr** [comment]
> Screenshot has `me?/...`
> Try `me?current_password.../` 
> 
> I don't understand the comment about `APPEND_SLASH`. It is set to true.

I can't, it gets added automatically by django if I remove it

**Comment by Monstarrrr** [comment]
> Want to go with this unsafe practice for the MVP? The accounts get deleted anyway- still not great to have links with passwords in them clientside though
> 
> Alternative is a custom View/APIView for account deletion

I mention this because we may not want to spend too much time trying to fix this in this way and maybe we could investigate an easier alternative if it exists like removing the requesting of a password on the endpoint for example.

**Comment by seporterfield** [comment]
> If I want to remove it I need to disable `APPEND_SLASH` else django replaces it automatically in the URL.

By "it" do you mean the final slash? Why remove it at all? `me?.../` works, I can't reproduce any issue with that.

**Comment by seporterfield** [comment]
> http://localhost:8000/auth/users/me?current_password=Password123 returns `404` ...

Wait, you may be confusing two different things.

What method are you using? GET or DELETE?

Use the correct method to make a call to
`http://localhost:8000/auth/users/me?current_password=Password123/` and post the error

**Comment by seporterfield** [comment]
Since the request is a DELETE method, do the objections about the password being in the params still make sense?

**Comment by Monstarrrr** [comment]
> > If I want to remove it I need to disable `APPEND_SLASH` else django replaces it automatically in the URL.
> 
> By "it" do you mean the final slash? Why remove it at all?
> 
> I can't reproduce any issue with `me?.../`
> 
> 

I tried with removing it because i've never seen query strings in URLs being used without a path next to it (I've seen this: ``domain.com/path?queryString=whatever`` but never ``domain.com/path/?queryString=whatever``)  
https://www.rfc-editor.org/rfc/rfc1738#section-3.3  

It could be unrelated though

**Comment by Monstarrrr** [comment]
> 
> > http://localhost:8000/auth/users/me?current_password=Password123 returns `404` ...
> 
> Wait, you may be confusing two different things.
> 
> What method are you using? GET or DELETE?
> 
> Use the correct method to make a call to
> `http://localhost:8000/auth/users/me?current_password=Password123/` and post the error 

I'm using ``delete``

**Comment by Monstarrrr** [comment]
> Since the request is a DELETE method, do the objections about the password being in the params still make sense?

[It seems so](https://stackoverflow.com/a/65395066),  even though I don't care about it for the MVP, I still think it implies spending time looking for a solution we won't keep for long anyways so maybe we should look at alternatives

**Comment by seporterfield** [comment]
I don't see anything in that thread answer related to security or the objections mentioned in the previous article.

**Comment by seporterfield** [comment]
> I still think it implies spending time looking for a solution we won't keep for long anyways so maybe we should look at alternatives

👍 👍 👍 Yes

**Comment by seporterfield** [comment]
By default djoser has the setting
`"user_delete": "djoser.serializers.UserDeleteSerializer"`, in the `SERIALIZERS` sub-setting
We can make a new serializer and keep the same route, but with an actual sensible way of passing values to the API
And one that drf-spectacular will be able to detect and add to the documentation.
