### ISSUE TITLE
Argument creation, read, update, delete

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#255]
Write ~~and add tests for~~ the following routes.
If they exist already, modify them so they fit our schema.

- arguments
- arguments/add
- arguments/{id}
- arguments/{id}/delete
- arguments/{id}/edit

update from @purple-void:
@Monstarrrr mentioned arguments/add and arguments/{id}/delete are old endpoints. the other endpoints have been created.

**Comment by Monstarrrr** [comment]
Based on what we said about shadow submissions, it seems we'll need a process to have arguments in a ''pending'' state on the backend, don't we then need an other admin-only endpoint to validate them?

**Comment by Monstarrrr** [comment]
> @Monstarrrr what do you mean shadow submissions and pending state?

When someone post an argument, they see it on our website instantly but no one else sees it until we have accepted it (to prevent abusive content and spam during MVP), that's what I mean by shadow submissions.  
The pending state is the state during which a post is pending admin verification.

**Comment by Monstarrrr** [comment]
> How will admin verification work? Is it manual?

Yes but my question was do we change it in the DB directly or do we use an endpoint
