### ISSUE TITLE
Argument votes

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#257]
Write and add tests for the following routes.
If they exist already, modify them so they fit our schema.

- [x] arguments/{id}/upvote
- [x] arguments/{id}/upvote/undo
- [x] arguments/{id}/downvote
- [x] arguments/{id}/downvote/undo
- [x] tests

blocked by #293

**Comment by seporterfield** [comment]
@ndharmateja all yours

**Comment by ndharmateja** [comment]
@Monstarrrr what should be the response body for these routes?

**Comment by ndharmateja** [comment]
@Monstarrrr also I am unable to move this issue to "In Progress"
is it because of permissions? 🤔

**Comment by ndharmateja** [comment]
@seporterfield @Monstarrrr @purple-void 
should the following edge cases be considered?
1. upvote argument
    - when the argument is already upvoted, should an error be raised?
2. upvote argument undo
    - if the existing vote is "downvote", what should be done?
    - if no vote between the user and argument exists, what should be done?

**Comment by Monstarrrr** [comment]
> @Monstarrrr what should be the response body for these routes?

I am in the process of building the Mock API which will contain the response format i'm looking for.  
I will let you know asap.  
If an issue is blocked by an other it may be a good idea to add ''blocked by #[issue_number]" in the issue body to help with keeping track of dependencies.

**Comment by Monstarrrr** [comment]
> @seporterfield @Monstarrrr @purple-void 
> should the following edge cases be considered?
> 1. upvote argument
>     - when the argument is already upvoted, should an error be raised?
> 2. upvote argument undo
>     - if the existing vote is "downvote", what should be done?
>     - if no vote between the user and argument exists, what should be done?

1. In theory i'll make sure an upvote cast can't happen if the item is already upvoted, in practice if it were to happen then we'd expect an error yes  

2.1. If existing vote is a downvote then there is no upvote to undo, so likewise such a call would return an error  

2.2 If no vote exists then there can't be votes to undo, so this is an error too

**Comment by ndharmateja** [comment]
> > @Monstarrrr what should be the response body for these routes?
> 
> I am in the process of building the Mock API which will contain the response format i'm looking for. I will let you know asap. If an issue is blocked by an other it may be a good idea to add ''blocked by #[issue_number]" in the issue body to help with keeping track of dependencies.

okay great
I added the blocked by.

**Comment by ndharmateja** [comment]
> > @seporterfield @Monstarrrr @purple-void
> > should the following edge cases be considered?
> > 
> > 1. upvote argument
> >    
> >    * when the argument is already upvoted, should an error be raised?
> > 2. upvote argument undo
> >    
> >    * if the existing vote is "downvote", what should be done?
> >    * if no vote between the user and argument exists, what should be done?
> 
> 1. In theory i'll make sure an upvote cast can't happen if the item is already upvoted, because clicking this upvote will trigger a `/undo`, in practice if it were to happen for whatever reason then we'd expect an error
> 2. If existing vote is a downvote then there is no upvote to undo, so likewise such a call would return an error
> 3. If no vote exists then there can't be votes to undo, so this is an error too
> 
> Let me know if I that makes sense to you too

yes
definitely makes sense 👍🏼

**Comment by Monstarrrr** [comment]
In general you can assume that anything not explicitly planned is an error, kind of like the  https://csrc.nist.rip/glossary/term/deny_by_default approach
