### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#268]
## Frontend

- [ ] Self-account deletion
- [ ] Password change

**Comment by seporterfield** [comment]
@Monstarrrr Do "Username" and "Posts List" from the whitepaper belong here too?

**Comment by Monstarrrr** [comment]
No this is just settings, shouldn't be called ''page'' because in the MVP it's probably just going to be on the same page as profile

**Comment by seporterfield** [comment]
Ok, moved these features to #269. Closing.
