### ISSUE TITLE
Need to receive the proper schema for POST ``api/posts``

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#364]
## Problem
I can't use proper error handling (currently it works for ``api/posts/?type=argument`` but I can't make it work for ``api/posts/?type=rebuttal`` as well because the API returns a different schema while the front-end uses the same function for both.  
I could make a temp fix but we'll waste a bit more time later on so might as well fix it now  
## Solution
Send me the same schema for both ``api/posts/?type=argument`` and ``api/posts/?type=rebuttal`` (preferably following the white paper)  

ty king <3

**Comment by seporterfield** [comment]
Here are cropped versions of the responses I get for each request with type=argument and type=rebuttal

```json
{
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 12,
      "type": "rebuttal",
      "isPrivate": false,
      "body": "your mom",
      "title": "Some title",
      "ownerUserId": 8,
      "parentId": 9,
      "created": "2024-12-05T16:05:36.999520Z",
      "updated": "2024-12-05T16:05:36.999536Z",
      "upvotes": 0,
      "downvotes": 0
    }, ...]
}
```

```json
{
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 24,
      "type": "argument",
      "isPrivate": false,
      "body": "Source: ???",
      "title": "Ziggy is a lizard confirmed",
      "ownerUserId": 2,
      "parentId": null,
      "created": "2024-12-05T21:12:23.622795Z",
      "updated": "2024-12-05T21:12:23.622812Z",
      "upvotes": 0,
      "downvotes": 0
    }, ...]
}
```
