### ISSUE TITLE
unclear error message when trying to edit email to the same email

### ISSUE THREAD

**Issue by rebutify-developer** [Monstarrrr/rebutify#408]
## Problem
"Some field is not being recognized, check logs."

## Solution
change error message to something similar to "You cannot edit the email to your current email."

**Comment by Monstarrrr** [comment]
I can't reproduce this, it just successfully updates  
![Image](https://github.com/user-attachments/assets/e7e54678-9e23-4b57-8e37-25ffe3ae47b0)

**Comment by Monstarrrr** [comment]
> We realize now that there wasn't a check for updating to the same email. We wrote one in [this pull request](https://github.com/Monstarrrr/rebutify/pull/410), in which we return ` "code": 400, "message": "Email already in use", "errors": [ "This email is already associated with this account" ], }`. We recommend waiting to fix this until that pull request is merged.

That's fine but the array for field errors is ``formErrors`` not ``errors`` ^^  
(https://docs.google.com/document/d/1YD5JONwXirWWoSGQblhfEtk968Ux9Y2Sgw0Dd9XnpuI/edit?tab=t.0#heading=h.a3djhzh2iij6)

**Comment by Monstarrrr** [comment]
#414 
#415
