### ISSUE TITLE
Implement refresh token

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#41]
- [x] Generate refresh token on backend
- [x] Handle refresh token on frontend

**Comment by seporterfield** [comment]
Could [this](https://medium.com/@nandagopal05/using-axios-interceptors-to-automate-refreshing-access-tokens-c3c344737bcc) be a potential solution?

**Comment by Monstarrrr** [comment]
> Could [an axios interceptor](https://medium.com/@nandagopal05/using-axios-interceptors-to-automate-refreshing-access-tokens-c3c344737bcc) be a potential solution?

Yep, this issue was for generating a refresh token on the backend, so it is done
