### ISSUE TITLE
Account activation

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#48]
### Flow 
1. User registers (``/register``)
2. "A verification email has been sent - You can close this page" (modal)
3. Email verification page 
    3.1. Retrieve JWT token - URL we want to receive: ``localhost:3000/verify?token=[theToken]``
    3.2. ``post /auth/jwt/verify``   
    - 3.2.a.  **Success**: redirects to ``/`` 
    - 3.2.b.  **Fail**: Verification page with error message (e.g. "Verification link expired") (``/verify``)

~~Blocked by #52~~

**Comment by seporterfield** [comment]
>        3.1. Retrieve JWT token - URL we want to receive: `localhost:3000/verify?token=[theToken]`
>        3.2. `post /auth/jwt/verify`

This is wrong endpoint. It should be `post /auth/users/activation`

**Comment by Monstarrrr** [comment]
@seporterfield 
I know this has changed since the first time you mentioned it, so where do I put the "email activation URL" in the format I need for the front-end ?  
I'll need the following: ``localhost:3000/activate?uid=myUID&token=myToken``

**Comment by seporterfield** [comment]
When you first apply migrations from our app to an empty database Django will set the site's domain to `example.com`.

To set it to `localhost:3000`, add it to your .env assigned to `FRONTEND_SITE_URL`.

Then update the site url in the database.
I added a simple way of doing this using the Django shell and a script:
`python manage.py shell < scripts/update_site_domain.py`

After this, the site's domain in the DB should be `localhost:3000`.

Now the link will show up as you want.

**Comment by seporterfield** [comment]
```sh
python manage.py migrate
python manage.py shell < scripts/update_site_domain.py
```
and in another shell
```sh
curl -X POST http://localhost:8000/auth/users/ -H "Content-Type: application/json"  -d '{"username":"ziggy","email":"<email>","password":"your_password123!"}'
```
Result:
![image](https://github.com/Monstarrrr/rebutify/assets/107010978/194e08f8-c813-45a7-8ee9-41f27871ef43)
