### ISSUE TITLE
Decision on API standard

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#66]
https://www.saaspegasus.com/guides/modern-javascript-for-django-developers/apis/#rest-vs-graphql

**Comment by seporterfield** [comment]
I'm sure graphql has amazing benefits.
Is the switch and learning curve really worth slowing down our development speed for?

It would mean extra work and non dev time learning on the backend and frontend, and lots of switching tooling to fit with graphql.
If the benefits can't outweigh the cost, we should stick with REST/plain JSON

**Comment by Monstarrrr** [comment]
> I'm sure graphql has amazing benefits. Is the switch and learning curve really worth slowing down our development speed for?
> 
> It would mean extra work and non dev time learning on the backend and frontend, and lots of switching tooling to fit with graphql. If the benefits can't outweigh the cost, we should stick with REST/plain JSON

I guess you just typed the decision file's statement and problematic 👌  
Can you add it to the file?

**Comment by Monstarrrr** [comment]
@purple-void Just looking for your opinion on this so I take it into account while creating the decision doc
