### ISSUE TITLE
Decision on Rebutify's License

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#68]
**Guide**: [3 Main Types of Open Source Licenses ](https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633#tldr---the-bsd-3-clause-license-should-do)

**Note**: [License Setting URL](https://github.com/Monstarrrr/rebutify/community)

**Comment by purple-void** [comment]
["MIT License (as far as I understand): Do whatever you want, but include a copy of the license."](https://www.reddit.com/r/opensource/comments/vmrseh/comment/ie2w791/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
we like this option the best of the three, although we don't care about someone including a copy of the license

**Comment by seporterfield** [comment]
@purple-void @Monstarrrr MIT
