### ISSUE TITLE
Open decision on technology for automating API docs

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#77]
## Technology for Automating API Docs

  - Impact: 🟡 Medium
  - Status: 🔓 Awaiting decision...
  - Deciders & Confidence:
    - @purple-void 3.5/5
    - @seporterfield [1 <-> 5] /5 5️
    - @Monstarrrr [1 <-> 5] /5 5️
- Technical Story: [related URLs] e.
    - #44
    - #73 
    - https://www.saaspegasus.com/guides/modern-javascript-for-django-developers/apis
- Last updated: [28-05-2024]

## Context and Problem Statement

What technology will we use to generate and serve an OpenAPI spec?

## Decision Drivers
- ease of use for front-end dev
- interoperability with tools relying on a standardized OpenAPI spec

## Considered Options

1.  [drf-spectacular](https://github.com/tfranzel/drf-spectacular)

This 2.2k star library is built to "extract as much schema information from DRF as possible".

- Good, because it is fast easy to implement (PR already done)
- Good, because it has strong community support
- Good, because authentication routes also show up in the spec
- Good, because it allows django to serve swagger ui which makes testing API routes simple
- Good, because it allows customizing the autogenerated documentation

2. Vanilla implementation

- Bad, because it would take very long

## Decision Outcome

Chosen option: drf-spectacular
Reason(s): only feasible option for our time

## Positive Consequences
- docs in both swagger and redoc UI formats
- new tooling we introduce can consume the docs via the corresponding endpoint

**Comment by purple-void** [comment]
A lot of Reddit comments mention that OpenAPI is good but not great.

[https://www.reddit.com/r/node/comments/1879tg4/i_spent_a_few_days_testing_out_every_api_docs/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)
[https://www.reddit.com/r/rails/comments/1bmydww/comment/kwewhdu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)
[https://www.reddit.com/r/django/comments/182t9wj/comment/kaqby9n/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)

Seems fine enough for us.
