### ISSUE TITLE
Change site name to URL of frontend

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#83]
The URL that users receive in activation and password reset emails should, in production, be the URL of the frontend server.

- [x] Add the frontend Url to the env template
- [x] Get the frontend url environment variable in settings.py
- [ ] [Change the site name in admin.py](https://forum.djangoproject.com/t/change-site-name-in-password-reset-email/11127/4) by importing the newly created setting (from django.comf import settings, settings.<NEW VAR>
- [x] Runs
- [x] Test: activation email contains the frontend url

**Comment by seporterfield** [comment]
https://github.com/Monstarrrr/rebutify/pull/76#pullrequestreview-2083652859

**Comment by seporterfield** [comment]
Can't implement the change as originally imaged.

Based on whether Djangos sites framework is activated there are two possible outcomes:
- (deactivated) The Django server uses its own hostname for the site url which is incorrect, since it needs to be the frontend
- (activated) Django stores the site url sent to the user by email in the database.

While testing locally you really need to go to localhost:8000/<admin path>/sites/site/1/change/ and manually alter the entry-- since it's not some value passed to the app at startup. No, it's in the database.

So, getting the frontend URL to show up in emails isn't a code feature, it's a manual process that would happen only once in our production database.

This issue can be closed by #76 merging.

**Comment by Monstarrrr** [comment]
> While testing locally you really need to go to localhost:8000//sites/site/1/change/ and manually alter the entry-- since it's not some value passed to the app at startup. No, it's in the database.

The link doesn't work for me, can you add the full process on how to manually alter the local database entries ?

**Comment by seporterfield** [comment]
Either use `python manage.py shell` and use the [Django ORM](https://docs.djangoproject.com/en/5.0/topics/db/queries/).
An automated version of this is in `scripts/`.

Or navigate to sites/site/ of the admin panel. You can get to the admin panel by going to the path set in `DJANGO_ADMIN_PATH` in your .env file.

There you can edit
