### ISSUE TITLE
Unit Tests for Continuous Delivery (Backend)

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#93]
Run backend unit tests upon merge.
Fail build if tests fail.

**Comment by seporterfield** [comment]
Proposal: use GitHub environments in place of .env files (since they're not committed)

[Creating an environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment)

[Using an environment in a workflow](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment) (same link)

**Comment by Monstarrrr** [comment]
> Proposal: use GitHub environments in place of .env files (since they're not committed)
> 
> [Creating an environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment)
> 
> [Using an environment in a workflow](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment) (same link)
> 
> 
Good proposal but why in a comment of this issue?

**Comment by seporterfield** [comment]
Cause it's specific to GitHub workflows.
Right now the default variables *might* work, but more complex CI flows will need GitHub environments.
I still expect a crash if we don't set the DJANGO_SECRET_KEY in a GitHub environment used by this workflow.

**Comment by seporterfield** [comment]
Automated testing is essential! Plenty of studies prove this, including the annual State of DevOps Report which regularly shows that outfits that don't test are low performers.

Here's a quickie on CI/CD and automated testing
https://www.youtube.com/watch?v=scEDHsr3APg

If you want to set up a separate CI/CD server and use something other than GitHub actions, by all means we can try it if it's a net benefit. Right now Github Actions would be the quickest and most convenient.

**Comment by seporterfield** [comment]
> We hate having the code rely on GitHub and thus Microsoft.

To be clear, none of the code for our application relies on GitHub

**Comment by purple-void** [comment]
how does our application work without the environmental variables? which would be in GitHub environments

**Comment by purple-void** [comment]
we discussed in discord. we are fine with this decision
